/**
 * Test untuk article-auditor.ts — Quality Assurance Layer
 * Cover: format validation, auto-fix, watermark, closing, limits, duplicates
 */
import { describe, it, expect } from "vitest";
import {
  auditArticle,
  auditBeforePublish,
  validateArticleForDiscord,
} from "../src/article-auditor";
import { Article } from "../src/article-writer";

// ─── Helper: Create test article ──────────────────────────

function makeArticle(overrides?: Partial<Article>): Article {
  return {
    title: "🔥 Test Article",
    intro: "Ini intro test",
    sections: [
      {
        heading: "📖 Section 1",
        body: "Ini body section 1 yang cukup panjang untuk test. Anime ini lagi ramai dibicarakan.",
        image_query: "test anime key visual",
        video_query: "test anime trailer",
      },
    ],
    category: "anime",
    ...overrides,
  };
}

// ─── Tests: auditArticle ─────────────────────────────────

describe("auditArticle", () => {
  it("should pass for valid article", () => {
    const article = makeArticle();
    const report = auditArticle(article);
    expect(report.passed).toBe(true);
    expect(report.criticalCount).toBe(0);
  });

  it("should fail for empty sections", () => {
    const article = makeArticle({ sections: [] });
    const report = auditArticle(article);
    expect(report.passed).toBe(false);
    expect(report.criticalCount).toBeGreaterThan(0);
    expect(report.issues.some(i => i.message.includes("tidak memiliki section"))).toBe(true);
  });

  it("should auto-fix empty heading", () => {
    const article = makeArticle();
    article.sections[0].heading = "";
    const report = auditArticle(article);
    expect(report.passed).toBe(true);
    expect(report.autoFixedCount).toBeGreaterThan(0);
    expect(report.article.sections[0].heading).toBe("📖");
  });

  it("should auto-fix empty body", () => {
    const article = makeArticle();
    article.sections[0].body = "";
    const report = auditArticle(article);
    expect(report.passed).toBe(true);
    expect(report.autoFixedCount).toBeGreaterThan(0);
    expect(report.article.sections[0].body.length).toBeGreaterThan(0);
  });

  it("should auto-fix bullet lists in body", () => {
    const article = makeArticle();
    article.sections[0].body = "- Poin 1\n- Poin 2\n- Poin 3";
    const report = auditArticle(article);
    expect(report.passed).toBe(true);
    expect(report.autoFixedCount).toBeGreaterThan(0);
    // Body should no longer start with bullet
    expect(report.article.sections[0].body).not.toMatch(/^[-•*]\s/m);
  });

  it("should auto-fix closing phrases (standalone line)", () => {
    const article = makeArticle();
    article.sections[0].body = "Anime ini keren sekali.\nKesimpulannya.";
    const report = auditArticle(article);
    expect(report.passed).toBe(true);
    expect(report.article.sections[0].body).not.toContain("Kesimpulannya.");
  });

  it("should detect duplicate headings", () => {
    const article = makeArticle();
    article.sections.push({
      heading: "📖 Section 1", // duplicate!
      body: "Body berbeda untuk section kedua yang cukup panjang.",
      image_query: "",
      video_query: "",
    });
    const report = auditArticle(article);
    expect(report.issues.some(i => i.message.includes("heading duplikat"))).toBe(true);
  });

  it("should detect duplicate body", () => {
    const article = makeArticle();
    const dupBody = "Ini body yang sama persis untuk testing duplicate detection. Panjang lebih dari 20 karakter.";
    article.sections[0].body = dupBody;
    article.sections.push({
      heading: "📖 Section 2",
      body: dupBody,
      image_query: "",
      video_query: "",
    });
    const report = auditArticle(article);
    expect(report.issues.some(i => i.message.includes("body mirip"))).toBe(true);
  });
});

// ─── Tests: Watermark Detection via auditArticle ─────────

describe("Watermark Detection", () => {
  it("should strip 'Artikel Lumina' watermark from article", () => {
    const article = makeArticle();
    article.title = "🔥 Anime News ✨ Artikel Lumina";
    const report = auditArticle(article);
    expect(report.article.title).not.toContain("Lumina");
  });

  it("should strip '[generated by AI]' watermark from article", () => {
    const article = makeArticle();
    article.intro = "Anime ini bagus [generated by AI]";
    const report = auditArticle(article);
    expect(report.article.intro).not.toContain("[generated by AI]");
  });

  it("should strip 'Scheduled Content' watermark from body", () => {
    const article = makeArticle();
    article.sections[0].body = "Info anime yang bagus. Scheduled Content";
    const report = auditArticle(article);
    expect(report.article.sections[0].body).not.toContain("Scheduled Content");
  });

  it("should NOT strip normal text with 'follow'", () => {
    const article = makeArticle();
    article.intro = "Follow our channel for more anime news!";
    const report = auditArticle(article);
    expect(report.article.intro).toBe("Follow our channel for more anime news!");
  });
});

// ─── Tests: Garbage Characters via auditArticle ───────────

describe("Garbage Characters", () => {
  it("should clean null characters from article", () => {
    const article = makeArticle();
    article.intro = "Anime\0ini\0keren";
    const report = auditArticle(article);
    expect(report.article.intro).not.toContain("\0");
  });

  it("should clean zero-width spaces from article", () => {
    const article = makeArticle();
    article.intro = "Anime\u200Bini\u200Ckeren";
    const report = auditArticle(article);
    expect(report.article.intro).not.toContain("\u200B");
    expect(report.article.intro).not.toContain("\u200C");
  });

  it("should NOT remove emoji", () => {
    const article = makeArticle();
    article.intro = "🔥 Anime Keren 🎬";
    const report = auditArticle(article);
    expect(report.article.intro).toContain("🔥");
    expect(report.article.intro).toContain("🎬");
  });

  it("should NOT remove normal Unicode (Japanese)", () => {
    const article = makeArticle();
    article.intro = "アニメが面白い";
    const report = auditArticle(article);
    expect(report.article.intro).toBe("アニメが面白い");
  });
});

// ─── Tests: Discord Limits ────────────────────────────────

describe("Discord Limits", () => {
  it("should truncate title over 256 chars", () => {
    const article = makeArticle();
    article.title = "A".repeat(300);
    const report = auditArticle(article);
    expect(report.article.title.length).toBeLessThanOrEqual(256);
  });

  it("should truncate body over 2000 chars", () => {
    const article = makeArticle();
    article.sections[0].body = "A".repeat(2500);
    const report = auditArticle(article);
    expect(report.article.sections[0].body.length).toBeLessThanOrEqual(2000);
  });
});

// ─── Tests: Media Validation ──────────────────────────────

describe("Media Validation", () => {
  it("should detect invalid YouTube URL", () => {
    const article = makeArticle();
    const media = [
      { type: "video", sectionIndex: 0, url: "https://example.com/video", caption: "" },
    ];
    const report = auditArticle(article, media);
    expect(report.passed).toBe(false);
    expect(report.issues.some(i => i.message.includes("bukan YouTube yang valid"))).toBe(true);
  });

  it("should accept valid YouTube URL", () => {
    const article = makeArticle();
    const media = [
      { type: "video", sectionIndex: 0, url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", caption: "" },
    ];
    const report = auditArticle(article, media);
    expect(report.issues.some(i => i.message.includes("bukan YouTube yang valid"))).toBe(false);
  });

  it("should accept valid YouTube short URL", () => {
    const article = makeArticle();
    const media = [
      { type: "video", sectionIndex: 0, url: "https://youtu.be/dQw4w9WgXcQ", caption: "" },
    ];
    const report = auditArticle(article, media);
    expect(report.issues.some(i => i.message.includes("bukan YouTube yang valid"))).toBe(false);
  });

  it("should detect duplicate video URLs", () => {
    const article = makeArticle();
    const media = [
      { type: "video", sectionIndex: 0, url: "https://www.youtube.com/watch?v=abc12345678", caption: "" },
      { type: "video", sectionIndex: 1, url: "https://www.youtube.com/watch?v=abc12345678", caption: "" },
    ];
    const report = auditArticle(article, media);
    expect(report.issues.some(i => i.message.includes("duplikat"))).toBe(true);
  });

  it("should detect duplicate image URLs", () => {
    const article = makeArticle();
    const media = [
      { type: "image", sectionIndex: 0, url: "https://example.com/img.jpg", caption: "" },
      { type: "image", sectionIndex: 1, url: "https://example.com/img.jpg", caption: "" },
    ];
    const report = auditArticle(article, media);
    expect(report.issues.some(i => i.message.includes("Image URL duplikat"))).toBe(true);
  });
});

// ─── Tests: auditBeforePublish ────────────────────────────

describe("auditBeforePublish", () => {
  it("should return article and report", () => {
    const article = makeArticle();
    const result = auditBeforePublish(article);
    expect(result.article).toBeDefined();
    expect(result.report).toBeDefined();
    expect(result.media).toBeDefined();
  });

  it("should log audit summary", () => {
    const article = makeArticle();
    // Should not throw
    const result = auditBeforePublish(article);
    expect(result.report.summary).toBeDefined();
    expect(typeof result.report.summary).toBe("string");
  });
});

// ─── Tests: validateArticleForDiscord ─────────────────────

describe("validateArticleForDiscord", () => {
  it("should return ok for valid article", () => {
    const article = makeArticle();
    const result = validateArticleForDiscord(article);
    expect(result.ok).toBe(true);
  });

  it("should return not ok for empty sections", () => {
    const article = makeArticle({ sections: [] });
    const result = validateArticleForDiscord(article);
    expect(result.ok).toBe(false);
    expect(result.issues.length).toBeGreaterThan(0);
  });

  it("should return issues array for invalid article", () => {
    const article = makeArticle({ sections: [] });
    const result = validateArticleForDiscord(article);
    expect(result.issues.some(i => i.includes("error") || i.includes("🛑"))).toBe(true);
  });
});

// ─── Tests: EYD Check ────────────────────────────────────

describe("EYD Check", () => {
  it("should warn about missing space after period", () => {
    const article = makeArticle();
    article.intro = "Anime ini bagus.Sekarang kita bahas.";
    const report = auditArticle(article);
    // Should have EYD warning about space after period
    expect(report.issues.some(i => i.message.includes("Spasi setelah tanda baca"))).toBe(true);
  });

  it("should warn about lowercase after period", () => {
    const article = makeArticle();
    article.intro = "Anime ini bagus. sekarang kita bahas.";
    const report = auditArticle(article);
    expect(report.issues.some(i => i.message.includes("Huruf kecil setelah titik"))).toBe(true);
  });

  it("should warn about excessive spacing", () => {
    const article = makeArticle();
    article.intro = "Anime   ini   bagus";
    const report = auditArticle(article);
    expect(report.issues.some(i => i.message.includes("Spasi berlebih"))).toBe(true);
  });
});
