import type { Article, ContentBrief, ContentDepth } from '../types/content';
import type { Env } from '../../types/env';
import { OllamaSource } from '../research/sources/ollama-source';
import { BudgetTracker } from '../../core/budget-tracker';
import { traceLog } from '../../core/trace-logger';

const BANNED_PHRASES = [
  'kesimpulannya', 'dapat disimpulkan', 'demikian artikel',
  'sekian', 'terima kasih', "that's all", 'semoga bermanfaat',
  'generated by ai', 'as an ai', 'i am an ai', 'sebagai ai',
  'pada artikel ini kita akan', 'halo semua',
];

export interface AuditResult {
  passed: boolean;
  issues: string[];
  severity: 'none' | 'warning' | 'critical';
}

function getMinSections(depth: ContentDepth): number {
  const sections: Record<ContentDepth, number> = { quick: 2, standard: 3, deep: 5 };
  return sections[depth];
}

export async function auditArticleFromEnv(
  article: Article,
  brief: ContentBrief,
  env?: Env,
  budget?: BudgetTracker
): Promise<AuditResult> {
  const issues: string[] = [];

  // — Static checks — //

  // Structure
  if (!article.title || article.title.length < 10) issues.push('Title too short (<10 chars)');
  if (!article.intro || article.intro.length < 50) issues.push('Intro too short (<50 chars)');

  const minSections = getMinSections(brief.depth);
  if (article.sections.length < minSections) {
    issues.push(`Too few sections: ${article.sections.length} < ${minSections}`);
  }

  // Banned phrases
  const fullText = [article.intro, ...article.sections.map((s: { body: string }) => s.body)]
    .join(' ')
    .toLowerCase();

  for (const phrase of BANNED_PHRASES) {
    if (fullText.includes(phrase)) issues.push(`Banned phrase found: "${phrase}"`);
  }

  // Section quality
  for (const [i, sec] of article.sections.entries()) {
    if (!sec.heading || sec.heading.length < 3) issues.push(`Section ${i + 1}: empty heading`);
    if (!sec.body || sec.body.length < 30) issues.push(`Section ${i + 1}: body too short`);
  }

  // — Ollama Web Search verification (if available) — //
  if (env?.OLLAMA_WEB_SEARCH_KEY) {
    const ollama = new OllamaSource(env, budget ?? new BudgetTracker(10));
    try {
      // 1. Verify image descriptions are about real entities
      for (const [i, sec] of article.sections.entries()) {
        if (sec.imageDescription && sec.imageDescription.length > 10) {
          const claim = sec.imageDescription.replace(/^(gambar|image|visual|foto|fan art|screenshot)/i, '').trim();
          const result = await ollama.verifyClaim(claim);
          if (result.confidence === 'low' || (!result.verified && result.confidence === 'medium')) {
            issues.push(`Image description "${sec.imageDescription.slice(0, 60)}..." may be inaccurate`);
          }
        }
      }

      // 2. Verify topic/entity references exist
      const topicResult = await ollama.verifyClaim(brief.topic);
      if (topicResult.confidence === 'low') {
        issues.push(`Topic "${brief.topic}" could not be verified via web search`);
      }

      // 3. Check recency — topic must have 2026 references
      const recencyCheck = await ollama.checkRecency(brief.topic);
      if (!recencyCheck.isRecent) {
        issues.push(`Topic may be outdated — no 2026 references found in search`);
      } else {
        traceLog('info', 'Auditor', `Recency verified: ${recencyCheck.dateRef ?? 'likely recent'}`);
      }
    } catch (e) {
      traceLog('warn', 'Auditor', 'Ollama web search failed', { error: (e as Error).message });
    }
  } else {
    traceLog('debug', 'Auditor', 'OLLAMA_WEB_SEARCH_KEY not set — skipping web verification');
  }

  const hasCritical = issues.some(
    (i) => i.includes('Too few sections') || i.includes('Title too short') || i.includes('could not be verified')
  );

  return {
    passed: issues.length === 0,
    issues,
    severity: issues.length === 0 ? 'none' : hasCritical ? 'critical' : 'warning',
  };
}

// — Deprecated sync version — kept for backward compatibility with existing callers
// Use auditArticleFromEnv() instead for web search enabled auditing
export function auditArticle(article: Article, brief: ContentBrief): AuditResult {
  // Forward to async version without env — runs static checks only
  // We use a simple sync wrapper for the legacy signature
  const issues: string[] = [];

  if (!article.title || article.title.length < 10) issues.push('Title too short (<10 chars)');
  if (!article.intro || article.intro.length < 50) issues.push('Intro too short (<50 chars)');

  const minSections = getMinSections(brief.depth);
  if (article.sections.length < minSections) {
    issues.push(`Too few sections: ${article.sections.length} < ${minSections}`);
  }

  const fullText = [article.intro, ...article.sections.map((s: { body: string }) => s.body)]
    .join(' ')
    .toLowerCase();

  for (const phrase of BANNED_PHRASES) {
    if (fullText.includes(phrase)) issues.push(`Banned phrase found: "${phrase}"`);
  }

  for (const [i, sec] of article.sections.entries()) {
    if (!sec.heading || sec.heading.length < 3) issues.push(`Section ${i + 1}: empty heading`);
    if (!sec.body || sec.body.length < 30) issues.push(`Section ${i + 1}: body too short`);
  }

  const hasCritical = issues.some(
    (i) => i.includes('Too few sections') || i.includes('Title too short')
  );

  return {
    passed: issues.length === 0,
    issues,
    severity: issues.length === 0 ? 'none' : hasCritical ? 'critical' : 'warning',
  };
}

export function autoFixArticle(article: Article, audit: AuditResult): Article {
  let fixed = { ...article };

  // Fix banned phrases — remove them
  for (const phrase of BANNED_PHRASES) {
    fixed.intro = fixed.intro.replace(new RegExp(phrase, 'gi'), '');
    fixed.sections = fixed.sections.map((s: { heading: string; body: string; imageDescription?: string | null; videoUrl?: string | null; videoTitle?: string | null }) => ({
      ...s,
      body: s.body.replace(new RegExp(phrase, 'gi'), ''),
    }));
  }

  // Remove empty sections
  fixed.sections = fixed.sections.filter((s) => s.heading && s.body && s.body.length >= 30);

  return fixed;
}
