/**
 * writer.ts — AI Article Content Generator
 * v5.0 — Modular, research + generate + parse pipeline
 *
 * Flow:
 * 1. Research topic via WebScout (multi-source)
 * 2. Build prompt for AI
 * 3. Call AI via AiRouter
 * 4. Parse & validate JSON response
 * 5. Fallback chain on failure
 */

import type { Env } from '../types/env';
import type { Article, ArticleResearch, ArticleCategory } from '../types/article';
import { ARTICLE_COLORS } from '../config/discord';
import { WebScout } from '../workers/webscout';
import { AiRouter } from './router';

// ─── Research Module ───────────────────────────────────────

async function researchNews(topic: string, env: Env): Promise<string> {
	try {
		const webScout = new WebScout(env);
		const results = await webScout.search(topic, { maxResults: 5, useCache: false });

		if (results.length === 0) return '📰 Gunakan pengetahuan umum.';

		const lines = results.map(
			(r, i) =>
				`${i + 1}. [${r.source}] ${r.title}${r.snippet ? ` — ${r.snippet.slice(0, 120)}` : ''}`,
		);

		return `📰 **BERITA TERKINI:**\n${lines.join('\n')}`;
	} catch {
		return '📰 Gunakan pengetahuan umum.';
	}
}

async function researchReviews(topic: string, env: Env): Promise<string> {
	try {
		const webScout = new WebScout(env);
		// Single search — save subrequests
		const reviewRes = await webScout.search(`${topic} review`, { maxResults: 3, useCache: false }).catch(() => []);

		const allReviews: Array<{ title: string; url: string; snippet: string; source: string }> = [];
		const seen = new Set<string>();

		for (const item of reviewRes) {
			const key = item.url || item.title;
			if (!seen.has(key)) {
				seen.add(key);
				allReviews.push(item);
			}
		}

		const reviewLines = allReviews.slice(0, 8).map(
			(r, i) => `${i + 1}. [${r.source}] ${r.title} — ${r.snippet.slice(0, 150)}`,
		);

		if (reviewLines.length === 0) return '';
		return `💬 **REVIEWS & OPINIONS DARI INTERNET:**\n${reviewLines.join('\n')}`;
	} catch {
		return '';
	}
}

export async function researchArticle(topic: string, env: Env): Promise<ArticleResearch> {
	const [newsSummary, reviewSummary] = await Promise.all([
		researchNews(topic, env),
		researchReviews(topic, env),
	]);

	return {
		summary: newsSummary + (reviewSummary ? `\n\n${reviewSummary}` : ''),
		reviewSummary,
	};
}

// ─── Prompt Builder ────────────────────────────────────────

export function buildArticlePrompt(topic: string, summary: string, reviewSummary?: string): string {
	return [
		`**ROLE**`,
		``,
		`Kamu jurnalis anime yang nulis kayak lagi ngobrol sama temen di Discord server anime. Bukan reporter berita. Bukan akademisi. Lo yang excited kalau ada news bagus, dan lo yang jujur kalau sesuatu underwhelming.`,
		``,
		`**INPUT YANG DIKASIH**`,
		`- Topik: ${topic}`,
		`- Data/fakta: ${summary}`,
		reviewSummary ? `- Opini publik: ${reviewSummary}` : '',
		``,
		`**OUTPUT: JSON**`,
		`1–3 section. Tidak ada closing section.`,
		``,
		`{`,
		`  "title": "...",`,
		`  "intro": "...",`,
		`  "sections": [{`,
		`    "heading": "...",`,
		`    "body": "...",`,
		`    "image_query": "WAJIB DIISI — keyword gambar spesifik",`,
		`    "video_query": "WAJIB DIISI — keyword video spesifik"`,
		`  }],`,
		`  "category": "anime/manga/game/breaking/announcement/general"`,
		`}`,
		``,
		`**FORMAT TAMPILAN**`,
		`Tiap section tampil sebagai satu message berurutan:`,
		`[Judul] → [Gambar] → [Narasi] → [Video]`,
		`Separator --- antar section. Headline = embed.`,
		``,
		`**GAYA BAHASA — INI YANG PALING PENTING**`,
		``,
		`Tulis kayak ini:`,
		`"Oke jadi ternyata MAPPA beneran ngumumin season 2-nya, dan gue masih belum move on dari season 1 yang itu. Komunitas jelas split — sebagian hype banget, sebagian udah skeptis duluan karena jadwal yang kemarin."`,
		``,
		`Bukan kayak ini:`,
		`"MAPPA telah mengumumkan season kedua dari serial tersebut. Komunitas memiliki beragam pendapat mengenai hal ini."`,
		``,
		`Aturan konkret:`,
		`- Boleh pakai "gue/lo" atau "kita"`,
		`- Boleh pakai elipsis (...) kalau mau nambahin efek mikir`,
		`- Opini publik dikutip dengan cara yang manusiawi, bukan "netizen berpendapat bahwa"`,
		`- Kalau faktanya menarik, boleh react dulu sebelum jelasin`,
		`- Jangan pernah nulis "dapat disimpulkan bahwa"`,
		`- Tidak ada poin-poin/bullet. Semua prosa mengalir`,
		``,
		`**LARANGAN**`,
		`- Jangan karang fakta di luar data yang dikasih`,
		`- Tidak ada watermark, footer, atau label "generated by AI"`,
		`- Tidak ada closing/penutup di akhir artikel`,
		``,
		`BALAS HANYA JSON, tanpa teks lain!`,
	].filter(Boolean).join('\n');
}

// ─── JSON Parser — Robust ──────────────────────────────────

export function parseArticleJSON(raw: string): Article {
	if (!raw || raw.trim().length === 0) {
		throw new Error('Response AI kosong');
	}

	let cleaned = raw
		.replace(/!\[.*?\]\(.*?\)/g, '')
		.replace(/\[.*?\]\(.*?\)/g, '')
		.replace(/[\u0000-\u001F\u007F]/g, '')
		.trim();

	let parsed: any = null;

	// Strategy 1: Extract JSON object from text
	try {
		const m = cleaned.match(/\{[\s\S]*\}/);
		if (m) parsed = JSON.parse(m[0]);
	} catch { /* fall through */ }

	// Strategy 2: Remove URLs then retry
	if (!parsed) {
		try {
			const r = cleaned.replace(/https?:\/\/[^\s,"}\]]+/g, '[link]');
			const m = r.match(/\{[\s\S]*\}/);
			if (m) parsed = JSON.parse(m[0]);
		} catch { /* fall through */ }
	}

	// Strategy 3: Fix broken JSON
	if (!parsed) {
		try {
			const fixed = cleaned
				.replace(/(['"])?([a-zA-Z0-9_]+)(['"])?\s*:/g, '"$2":')
				.replace(/:\s*'([^']*)'/g, ':"$1"')
				.replace(/,\s*}/g, '}')
				.replace(/,\s*]/g, ']');
			const m = fixed.match(/\{[\s\S]*\}/);
			if (m) parsed = JSON.parse(m[0]);
		} catch { /* fall through */ }
	}

	if (!parsed) {
		throw new Error('AI gagal generate artikel valid — response bukan JSON');
	}

	// Validate sections
	if (!parsed.sections || !Array.isArray(parsed.sections) || parsed.sections.length === 0) {
		if (parsed.topics && Array.isArray(parsed.topics) && parsed.topics.length > 0) {
			parsed.sections = parsed.topics;
			delete parsed.topics;
		} else {
			parsed.sections = [
				{
					heading: '📖 Lanjutan',
					body: parsed.intro || 'Topik ini lagi hangat dibicarakan di komunitas.',
					image_query: '',
					video_query: '',
				},
			];
		}
	}

	// Normalize each section
	parsed.sections = parsed.sections.map((s: any) => ({
		heading: s.heading || '📖',
		body: s.body || s.text || s.content || '',
		image_query: s.image_query || '',
		video_query: s.video_query || '',
	}));

	return parsed as Article;
}

// ─── Color Mapping ─────────────────────────────────────────

export function getArticleColor(category: string): number {
	return ARTICLE_COLORS[category] || ARTICLE_COLORS.general;
}

// ─── AI Article Generator ──────────────────────────────────

export async function generateArticle(topic: string, research: ArticleResearch, env: Env): Promise<Article> {
	const router = new AiRouter(env);

	// Attempt 1: Full prompt with research data
	try {
		const prompt = buildArticlePrompt(topic, research.summary, research.reviewSummary);
		const raw = await router.creativeChat([{ role: 'user', content: prompt }]);
		const rawStr = typeof raw === 'string' ? raw : JSON.stringify(raw);
		return parseArticleJSON(rawStr);
	} catch { /* fall through */ }

	// Attempt 2: Simplified prompt, no review
	try {
		const simplePrompt = buildArticlePrompt(topic, research.summary, '');
		const raw = await router.creativeChat([{ role: 'user', content: simplePrompt }]);
		const rawStr = typeof raw === 'string' ? raw : JSON.stringify(raw);
		return parseArticleJSON(rawStr);
	} catch { /* fall through */ }

	// Attempt 3: Minimal prompt
	try {
		const minimalPrompt =
			`Buat artikel anime pendek tentang: ${topic}\n` +
			`BALAS HANYA JSON ini:\n` +
			`{\n` +
			`  "title": "[Emoji] Judul",\n` +
			`  "intro": "Hook 2 kalimat",\n` +
			`  "sections": [{"heading":"📖 Sub-judul","body":"Narasi singkat 3-4 kalimat","image_query":"judul anime key visual","video_query":"judul anime trailer"}],\n` +
			`  "category": "anime"\n` +
			`}\n` +
			`Gaya santai, tanpa kesimpulan. JANGAN tambah teks lain!`;
		const raw = await router.chat([{ role: 'user', content: minimalPrompt }]);
		const rawStr = typeof raw === 'string' ? raw : JSON.stringify(raw);
		return parseArticleJSON(rawStr);
	} catch {
		throw new Error('3x percobaan artikel gagal');
	}
}

export function generateFallbackArticle(topic: string): Article {
	return {
		title: `📰 ${topic.slice(0, 80)}`,
		intro: `Halo! Berikut ini rangkuman singkat tentang ${topic} yang lagi ramai dibahas. Cek yuk!`,
		sections: [
			{
				heading: '📖 Yang Perlu Kamu Tahu',
				body: `${topic} adalah salah satu topik yang lagi hangat dibicarakan di komunitas anime. Banyak yang ngomongin di berbagai forum dan media sosial. Yuk cek update terbarunya!`,
				image_query: topic,
				video_query: topic,
			},
		],
		category: 'general',
	} as Article;
}
