/**
 * article-auditor.ts — Quality Assurance Layer untuk Artikel Sebelum Dikirim 🛡️
 * 
 * Modul ini adalah GATEKEEPER terakhir sebelum artikel dikirim ke Discord.
 * Tugasnya: validasi, audit, auto-fix, dan filter konten yang gak sesuai.
 * 
 * Flow:
 *   Article + Media → [AUDITOR] → Validasi/Fix → Kirim
 *                     ↓
 *                 Laporan Audit (issues found, fixed, blocked)
 * 
 * Ceklist Validasi:
 * ✅ Format sesuai aturan atau gak
 * ✅ Ada gambar atau gak (warning kalo kosong tapi diminta)
 * ✅ Video link valid atau gak
 * ✅ Ada yang dobel (section/media) atau gak
 * ✅ Support Discord limits (2000 char per message, dll)
 * ✅ Ada error ASCII/Unicode garbage atau gak
 * ✅ Ada watermark atau teks terlarang atau gak
 * ✅ Body bukan bullet list (harus narasi)
 * ✅ Gak ada "Kesimpulannya" atau kata penutup formal
 */

import { Article } from "./article-writer";

// ─── Types ─────────────────────────────────────────────────

export interface AuditIssue {
  type: "error" | "warning";
  category: "format" | "content" | "media" | "platform" | "watermark" | "duplicate";
  message: string;
  location?: string;       // Misal: "section[0].heading", "media.video[1]"
  autoFixable: boolean;
  autoFixed?: boolean;
}

export interface AuditReport {
  passed: boolean;          // true = semua critical check ok
  issues: AuditIssue[];     // Semua masalah
  criticalCount: number;    // Jumlah error (bukan warning)
  warningCount: number;     // Jumlah warning
  autoFixedCount: number;   // Berapa yang ke-fix otomatis
  article: Article;         // Artikel yang sudah di-fix
  media: ValidatedMedia[];  // Media yang sudah divalidasi
  summary: string;          // Ringkasan audit
}

export interface ValidatedMedia {
  type: "image" | "video";
  sectionIndex: number;
  url: string | null;
  caption?: string;
  valid: boolean;
  reason?: string;
}

// ─── Constants — Prohibited Patterns ─────────────────────

// ⚠️ HANYA hapus watermark yg beneran PROMOSI/FOOTER.
// Pattern yg terlalu umum (follow, subscribe, powered by) TIDAK dihapus
// karena bisa muncul di teks natural.
const WATERMARK_PATTERNS: RegExp[] = [
  /✨\s*Artikel\s*[•·]?\s*Lumina/i,
  /✨\s*Lumina/i,
  /\[generated\s+by\s+AI\]/i,    // Hanya kalo dalam bracket [generated by AI]
  /--\s*generated\s+by\s+AI/i,     // Hanya kalo setelah --
  /Scheduled\s+(Content|Task)/i,    // Capitalized = footer
  /This\s+was\s+auto-generated/i,
  /bot\s+generated\s+content/i,
];

// ⚠️ HANYA hapus kalo SELURUH kalimat adalah closing phrase.
// Kalo closing phrase cuma di awal kalimat (masih ada lanjutan) — TETAP PERTAHANKAN!
const CLOSING_PATTERNS: RegExp[] = [
  /^kesimpulannya[.\s]*$/mi,         // Hanya "Kesimpulannya." doang
  /^demikian[\s\w]+terima kasih[.\s]*$/mi,  // "Demikian ... terima kasih."
  /^sekian[\s\w]+terima kasih[.\s]*$/mi,     // "Sekian ... terima kasih."
  /^terima kasih[.\s]*$/mi,           // Hanya "Terima kasih." doang
  /^that's\s+all[.\s]*$/i,           // Hanya "That's all."
  /^the\s+end[.\s]*$/i,              // Hanya "The end."
];

const BULLET_INDICATORS: RegExp[] = [
  /^[-•*]\s/m,     // Baris dimulai dengan -, •, *
  /^\d+\.\s/m,     // Baris dimulai dengan 1. 2. 3.
];

// ⚠️ HANYA buang character yg beneran rusak/broken.
// Unicode aesthetic (bold/italic/circled) dan emoji TETAP dipertahankan!
const GARBAGE_PATTERNS: RegExp[] = [
  /[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g,  // Control chars (NULL, BS, etc)
  /\uFFFD/g,       // Replacement character � (Unicode error)
  /[\uD800-\uDFFF]/g,  // Lone surrogate pairs (broken Unicode)
  /[\u200B-\u200D\uFEFF]/g, // Zero-width spaces, BOM (invisible chars)
];

// ─── YouTube URL Validator ────────────────────────────────

const YT_WATCH_REGEX = /^https?:\/\/(?:www\.)?youtube\.com\/watch\?v=([a-zA-Z0-9_-]{11})/;
const YT_SHORT_REGEX = /^https?:\/\/youtu\.be\/([a-zA-Z0-9_-]{11})/;

function isValidYouTubeUrl(url: string): boolean {
  return YT_WATCH_REGEX.test(url) || YT_SHORT_REGEX.test(url);
}

// ─── Image URL Validator ─────────────────────────────────

function isValidImageUrl(url: string): boolean {
  if (!url || !url.startsWith("http")) return false;
  // Cek ekstensi umum (kalo ada)
  const pathname = url.split("?")[0];
  const ext = pathname.split(".").pop()?.toLowerCase();
  if (ext && ["jpg", "jpeg", "png", "gif", "webp", "avif", "bmp", "svg"].includes(ext)) {
    return true;
  }
  // Kalo gak ada ekstensi, tapi URL valid — tetap anggep ok
  // (beberapa CDN kayak MAL/AniList gak pake ekstensi)
  return url.length > 10 && url.startsWith("http");
}

// ─── Text Cleaner ─────────────────────────────────────────

function stripWatermarks(text: string): string {
  let cleaned = text;
  for (const pattern of WATERMARK_PATTERNS) {
    cleaned = cleaned.replace(pattern, "").trim();
  }
  return cleaned;
}

function cleanGarbageChars(text: string): string {
  // HANYA buang character yg beneran RUSAK:
  // - Control chars (0x00-0x1F kecuali 0x09 tab, 0x0A newline, 0x0D carriage return)
  // - Replacement char U+FFFD (�)
  // - Lone surrogate pairs
  // - Zero-width spaces (kecuali sengaja buat formatting)
  // 
  // ✅ TETAP PERTAHANKAN: emoji, aesthetic Unicode, mathematical symbols,
  //   circled letters, fullwidth chars, regional indicators
  if (!text) return text;
  
  // Hanya buang yg beneran rusak — korbankan presisi demi keamanan
  let cleaned = text;
  for (const pattern of GARBAGE_PATTERNS) {
    cleaned = cleaned.replace(pattern, '');
  }
  return cleaned;
}

function stripClosingPhrases(text: string): string {
  // HANYA strip kalo closing phrase adalah satu-satunya konten di body
  // atau di akhir paragraf TERAKHIR (bukan di tengah!)
  const lines = text.split('\n').filter(l => l.trim());
  if (lines.length === 0) return text;
  
  // Cek baris terakhir aja — kalo baris terakhir adalah closing, hapus baris itu
  const lastLine = lines[lines.length - 1].trim();
  let isClosing = false;
  for (const pattern of CLOSING_PATTERNS) {
    if (pattern.test(lastLine)) {
      isClosing = true;
      break;
    }
  }
  
  if (isClosing) {
    // Hapus baris terakhir
    const remaining = lines.slice(0, -1).join('\n').trim();
    return remaining || text; // Kalo habis semua, return original
  }
  
  return text;
}

// ─── Discord Limit Checker ────────────────────────────────

const DISCORD_LIMITS = {
  messageContent: 2000,
  embedTitle: 256,
  embedDescription: 4096,
  embedFields: 25,
  embedFooter: 2048,
};

interface DiscordLimitCheck {
  ok: boolean;
  field: string;
  current: number;
  max: number;
}

function checkDiscordLimits(article: Article): DiscordLimitCheck[] {
  const checks: DiscordLimitCheck[] = [];

  // Embed title
  const titleLen = (article.title || "").length;
  if (titleLen > DISCORD_LIMITS.embedTitle) {
    checks.push({ ok: false, field: "title (embed)", current: titleLen, max: DISCORD_LIMITS.embedTitle });
  }

  // Embed description
  const introLen = (article.intro || "").length;
  if (introLen > DISCORD_LIMITS.embedDescription) {
    checks.push({ ok: false, field: "intro (embed description)", current: introLen, max: DISCORD_LIMITS.embedDescription });
  }

  // Section body per message
  for (let i = 0; i < article.sections.length; i++) {
    const bodyLen = (article.sections[i].body || "").length;
    if (bodyLen > DISCORD_LIMITS.messageContent) {
      checks.push({ ok: false, field: `section[${i}].body`, current: bodyLen, max: DISCORD_LIMITS.messageContent });
    }
    const headingLen = (article.sections[i].heading || "").length;
    if (headingLen > DISCORD_LIMITS.messageContent) {
      checks.push({ ok: false, field: `section[${i}].heading`, current: headingLen, max: DISCORD_LIMITS.messageContent });
    }
  }

  return checks;
}

// ─── EYD Indonesia Check ──────────────────────────────────
// Validasi dasar Ejaan Yang Disempurnakan
// Catatan: ini cek BASIC aja, bukan grammar checker full

interface EydIssue {
  type: "error" | "warning";
  message: string;
  location?: string;
}

function checkEyd(text: string, label: string): EydIssue[] {
  const issues: EydIssue[] = [];
  if (!text) return issues;
  
  // 1. Spasi setelah tanda baca (. , ! ?)
  const noSpaceAfterPunct = /[.!?][A-Za-z]/g;
  let m;
  while ((m = noSpaceAfterPunct.exec(text)) !== null) {
    // Kecuali kalo itu singkatan kayak "A.P." atau "U.S."
    const before = text[m.index - 1] || '';
    const after = text[m.index + 2] || '';
    if (before >= 'A' && before <= 'Z' && after >= 'A' && after <= 'Z') continue; // Might be an abbreviation
    issues.push({
      type: "warning",
      message: `Spasi setelah tanda baca diikuti huruf (${label})`,
      location: label,
    });
    break; // 1 warning cukup
  }
  
  // 2. Huruf kapital setelah titik
  const noCapAfterPeriod = /\.[\s]*[a-z]/g;
  if (noCapAfterPeriod.test(text)) {
    issues.push({
      type: "warning",
      message: `Huruf kecil setelah titik di "${label}" — harus kapital`,
      location: label,
    });
  }
  
  // 3. Spasi ganda
  if (/\s{3,}/.test(text)) {
    issues.push({
      type: "warning",
      message: `Spasi berlebih di "${label}"`,
      location: label,
    });
  }
  
  return issues;
}

// ─── Main Audit Function ──────────────────────────────────

/**
 * Audit artikel sebelum dikirim ke Discord.
 * Auto-fix masalah yang bisa di-fix, report sisanya.
 * 
 * @param article - Artikel hasil generate AI
 * @param mediaResults - Hasil pencarian media (optional, dari publisher)
 * @returns AuditReport dengan status + issues + fixed version
 */
export function auditArticle(
  article: Article,
  mediaResults?: Array<{ type: string; sectionIndex: number; url: string | null; caption?: string } | null>
): AuditReport {
  const issues: AuditIssue[] = [];
  let criticalCount = 0;
  let warningCount = 0;
  let autoFixedCount = 0;

  // Deep clone article biar gak mutate original
  const auditedArticle: Article = JSON.parse(JSON.stringify(article));
  const auditedMedia: ValidatedMedia[] = (mediaResults || []).map(m => {
    if (!m) return { type: "image", sectionIndex: -1, url: null, valid: false, reason: "null result" };
    return {
      type: m.type as "image" | "video",
      sectionIndex: m.sectionIndex,
      url: m.url,
      caption: m.caption,
      valid: true,
    };
  });

  const sections = auditedArticle.sections || [];

  // ════════════════════════════════════════════════════════
  // CHECK 1: FORMAT VALIDATION
  // ════════════════════════════════════════════════════════

  // 1a. Empty sections
  if (sections.length === 0) {
    issues.push({
      type: "error",
      category: "format",
      message: "Artikel tidak memiliki section!",
      location: "sections",
      autoFixable: false,
    });
    criticalCount++;
  }

  // 1b. Each section must have heading & body
  for (let i = 0; i < sections.length; i++) {
    const s = sections[i];
    if (!s.heading || s.heading.trim().length === 0) {
      s.heading = "📖";
      issues.push({
        type: "warning",
        category: "format",
        message: `Section[${i}] heading kosong, di-fix jadi "📖"`,
        location: `section[${i}].heading`,
        autoFixable: true,
        autoFixed: true,
      });
      warningCount++;
      autoFixedCount++;
    }
    if (!s.body || s.body.trim().length === 0) {
      s.body = s.heading ? `${s.heading} — topik yang lagi hangat dibicarakan.` : "Topik yang lagi hangat dibicarakan.";
      issues.push({
        type: "warning",
        category: "format",
        message: `Section[${i}] body kosong, diisi fallback`,
        location: `section[${i}].body`,
        autoFixable: true,
        autoFixed: true,
      });
      warningCount++;
      autoFixedCount++;
    }
  }

  // 1c. No bullet lists in body (harus narasi!)
  for (let i = 0; i < sections.length; i++) {
    const body = sections[i].body || "";
    for (const bullet of BULLET_INDICATORS) {
      if (bullet.test(body)) {
        // Convert bullet list ke narasi
        const lines = body.split("\n").filter(l => l.trim());
        const narrative = lines
          .map(l => l.replace(/^[-•*]\s*|\d+\.\s*/gm, "").trim())
          .filter(Boolean)
          .join(". ") + ".";
        sections[i].body = narrative;
        issues.push({
          type: "warning",
          category: "format",
          message: `Section[${i}] body mengandung bullet list, dikonversi ke narasi`,
          location: `section[${i}].body`,
          autoFixable: true,
          autoFixed: true,
        });
        warningCount++;
        autoFixedCount++;
        break;
      }
    }
  }

  // 1d. No closing phrases
  for (let i = 0; i < sections.length; i++) {
    const body = sections[i].body || "";
    const cleaned = stripClosingPhrases(body);
    if (cleaned !== body) {
      sections[i].body = cleaned;
      issues.push({
        type: "warning",
        category: "format",
        message: `Section[${i}] body mengandung frasa penutup, dihapus`,
        location: `section[${i}].body`,
        autoFixable: true,
        autoFixed: true,
      });
      warningCount++;
      autoFixedCount++;
    }
  }

  // ════════════════════════════════════════════════════════
  // CHECK 2: DUPLICATE DETECTION
  // ════════════════════════════════════════════════════════

  // 2a. Duplicate section headings
  const headingSet = new Set<string>();
  for (let i = 0; i < sections.length; i++) {
    const h = (sections[i].heading || "").toLowerCase().trim();
    if (headingSet.has(h) && h.length > 3) {
      issues.push({
        type: "warning",
        category: "duplicate",
        message: `Section[${i}] heading duplikat dengan section lain: "${sections[i].heading}"`,
        location: `section[${i}].heading`,
        autoFixable: false,
      });
      warningCount++;
    }
    headingSet.add(h);
  }

  // 2b. Duplicate section bodies
  const bodySet = new Set<string>();
  for (let i = 0; i < sections.length; i++) {
    const b = (sections[i].body || "").toLowerCase().trim().slice(0, 100);
    if (bodySet.has(b) && b.length > 20) {
      issues.push({
        type: "warning",
        category: "duplicate",
        message: `Section[${i}] body mirip dengan section lain`,
        location: `section[${i}].body`,
        autoFixable: false,
      });
      warningCount++;
    }
    bodySet.add(b);
  }

  // 2c. Duplicate media URLs
  const seenVideoUrls = new Set<string>();
  const seenImageUrls = new Set<string>();
  for (const m of auditedMedia) {
    if (!m || !m.url) continue;
    if (m.type === "video") {
      if (seenVideoUrls.has(m.url)) {
        m.valid = false;
        m.reason = "duplicate video URL";
        issues.push({
          type: "warning",
          category: "duplicate",
          message: `Video URL duplikat: ${m.url.slice(0, 50)}...`,
          location: `media.video[${m.sectionIndex}]`,
          autoFixable: true,
          autoFixed: true,
        });
        warningCount++;
        autoFixedCount++;
      }
      seenVideoUrls.add(m.url);
    } else if (m.type === "image") {
      if (seenImageUrls.has(m.url)) {
        m.valid = false;
        m.reason = "duplicate image URL";
        issues.push({
          type: "warning",
          category: "duplicate",
          message: `Image URL duplikat: ${m.url.slice(0, 50)}...`,
          location: `media.image[${m.sectionIndex}]`,
          autoFixable: true,
          autoFixed: true,
        });
        warningCount++;
        autoFixedCount++;
      }
      seenImageUrls.add(m.url);
    }
  }

  // ════════════════════════════════════════════════════════
  // CHECK 3: MEDIA VALIDATION
  // ════════════════════════════════════════════════════════

  // 3a. Validate image URLs
  for (const m of auditedMedia) {
    if (!m || !m.url || m.type !== "image" || !m.valid) continue;
    if (!isValidImageUrl(m.url)) {
      m.valid = false;
      m.reason = "invalid image URL format";
      issues.push({
        type: "error",
        category: "media",
        message: `Image URL tidak valid: ${m.url.slice(0, 60)}...`,
        location: `media.image[${m.sectionIndex}]`,
        autoFixable: false,
      });
      criticalCount++;
    }
  }

  // 3b. Validate video URLs (must be valid YouTube)
  for (const m of auditedMedia) {
    if (!m || !m.url || m.type !== "video" || !m.valid) continue;
    if (!isValidYouTubeUrl(m.url)) {
      m.valid = false;
      m.reason = "not a valid YouTube URL";
      issues.push({
        type: "error",
        category: "media",
        message: `Video URL bukan YouTube yang valid: ${m.url.slice(0, 60)}...`,
        location: `media.video[${m.sectionIndex}]`,
        autoFixable: false,
      });
      criticalCount++;
    }
  }

  // 3c. Check for missing media (section requests but none found)
  for (let i = 0; i < sections.length; i++) {
    const sec = sections[i];
    const secMedia = auditedMedia.filter(m => m && m.sectionIndex === i && m.valid);
    const hasVideo = secMedia.some(m => m.type === "video");
    const hasImage = secMedia.some(m => m.type === "image");

    // Warning kalo section punya video_query tapi gak ada video found
    if (sec.video_query && sec.video_query.length > 3 && !hasVideo) {
      issues.push({
        type: "warning",
        category: "media",
        message: `Section[${i}] minta video "${sec.video_query.slice(0, 40)}..." tapi gak ketemu`,
        location: `section[${i}].video_query`,
        autoFixable: false,
      });
      warningCount++;
    }

    // Warning kalo section punya image_query tapi gak ada image found
    if (sec.image_query && sec.image_query.length > 3 && !hasImage) {
      issues.push({
        type: "warning",
        category: "media",
        message: `Section[${i}] minta gambar "${sec.image_query.slice(0, 40)}..." tapi gak ketemu`,
        location: `section[${i}].image_query`,
        autoFixable: false,
      });
      warningCount++;
    }
  }

  // ════════════════════════════════════════════════════════
  // CHECK 4: CONTENT QUALITY — Garbage/ASCII
  // ════════════════════════════════════════════════════════

  // 4a. Clean garbage chars from all text fields
  const textFields = [
    { obj: auditedArticle, field: "title" },
    { obj: auditedArticle, field: "intro" },
    ...sections.map((_, i) => ({ obj: sections[i], field: "heading" })),
    ...sections.map((_, i) => ({ obj: sections[i], field: "body" })),
  ];

  for (const tf of textFields) {
    const val = (tf.obj as any)[tf.field];
    if (typeof val !== "string") continue;

    // Check for garbage
    let hasGarbage = false;
    for (const pattern of GARBAGE_PATTERNS) {
      if (pattern.test(val)) {
        hasGarbage = true;
        break;
      }
    }

    if (hasGarbage) {
      const cleaned = cleanGarbageChars(val);
      (tf.obj as any)[tf.field] = cleaned;
      issues.push({
        type: "warning",
        category: "content",
        message: `${tf.field} mengandung karakter kontrol/garbage, dibersihkan`,
        location: tf.field,
        autoFixable: true,
        autoFixed: true,
      });
      warningCount++;
      autoFixedCount++;
    }
  }

  // 4b. Strip watermarks from all text
  for (const tf of textFields) {
    const val = (tf.obj as any)[tf.field];
    if (typeof val !== "string") continue;

    const stripped = stripWatermarks(val);
    if (stripped !== val) {
      (tf.obj as any)[tf.field] = stripped;
      issues.push({
        type: "warning" as const,
        category: "watermark" as const,
        message: `Watermark terdeteksi & dihapus dari ${tf.field}`,
        location: tf.field,
        autoFixable: true,
        autoFixed: true,
      });
      warningCount++;
      autoFixedCount++;
    }
  }

  // 4c. Check for invisible/empty content after cleaning
  for (let i = 0; i < sections.length; i++) {
    if (!sections[i].body || sections[i].body.trim().length === 0) {
      sections[i].body = "Topik ini lagi hangat dibicarakan di komunitas anime.";
      issues.push({
        type: "warning",
        category: "content",
        message: `Section[${i}] body kosong setelah dibersihkan, diisi fallback`,
        location: `section[${i}].body`,
        autoFixable: true,
        autoFixed: true,
      });
      warningCount++;
      autoFixedCount++;
    }
  }

  // ════════════════════════════════════════════════════════
  // CHECK 5: PLATFORM COMPATIBILITY (Discord)
  // ════════════════════════════════════════════════════════

  const limitChecks = checkDiscordLimits(auditedArticle);
  for (const lc of limitChecks) {
    // Auto-fix: truncate to limit
    const parts = lc.field.split(".");
    if (parts[0] === "title") {
      auditedArticle.title = (auditedArticle.title || "").slice(0, DISCORD_LIMITS.embedTitle);
    } else if (parts[0] === "intro") {
      auditedArticle.intro = (auditedArticle.intro || "").slice(0, DISCORD_LIMITS.embedDescription);
    } else if (parts[0] === "section") {
      const idx = parseInt(parts[1]);
      if (!isNaN(idx) && auditedArticle.sections[idx]) {
        if (parts[2] === "body") {
          auditedArticle.sections[idx].body = (auditedArticle.sections[idx].body || "").slice(0, DISCORD_LIMITS.messageContent - 100);
        } else if (parts[2] === "heading") {
          auditedArticle.sections[idx].heading = (auditedArticle.sections[idx].heading || "").slice(0, DISCORD_LIMITS.messageContent - 100);
        }
      }
    }
    issues.push({
      type: "warning",
      category: "platform",
      message: `${lc.field} melebihi batas Discord (${lc.current} > ${lc.max}), di-truncate`,
      location: lc.field,
      autoFixable: true,
      autoFixed: true,
    });
    warningCount++;
    autoFixedCount++;
  }

  // ════════════════════════════════════════════════════════
  // CHECK 6: WATERMARK on title & intro (double check)
  // ════════════════════════════════════════════════════════

  for (const pattern of WATERMARK_PATTERNS) {
    if (pattern.test(auditedArticle.title || "")) {
      auditedArticle.title = stripWatermarks(auditedArticle.title || "");
      issues.push({
        type: "warning",
        category: "watermark",
        message: `Watermark pattern "${pattern.source}" dihapus dari title`,
        location: "title",
        autoFixable: true,
        autoFixed: true,
      });
      warningCount++;
      autoFixedCount++;
    }
    if (pattern.test(auditedArticle.intro || "")) {
      auditedArticle.intro = stripWatermarks(auditedArticle.intro || "");
      issues.push({
        type: "warning",
        category: "watermark",
        message: `Watermark pattern dihapus dari intro`,
        location: "intro",
        autoFixable: true,
        autoFixed: true,
      });
      warningCount++;
      autoFixedCount++;
    }
    for (let i = 0; i < sections.length; i++) {
      if (pattern.test(sections[i].body || "")) {
        sections[i].body = stripWatermarks(sections[i].body || "");
        issues.push({
          type: "warning",
          category: "watermark",
          message: `Watermark pattern dihapus dari section[${i}].body`,
          location: `section[${i}].body`,
          autoFixable: true,
          autoFixed: true,
        });
        warningCount++;
        autoFixedCount++;
      }
    }
  }

  // ════════════════════════════════════════════════════════
  // CHECK 7: EYD BAHASA INDONESIA
  // ════════════════════════════════════════════════════════

  // Basic EYD checks — auto-fix spacing issues
  const eydFields = [
    { text: auditedArticle.title, label: "title" },
    { text: auditedArticle.intro, label: "intro" },
    ...sections.map((s, i) => ({ text: s.body, label: `section[${i}].body` })),
  ];

  for (const ef of eydFields) {
    if (!ef.text) continue;
    const eydIssues = checkEyd(ef.text, ef.label);
    for (const ei of eydIssues) {
      issues.push({
        type: ei.type as "error" | "warning",
        category: "content",
        message: ei.message,
        location: ei.location,
        autoFixable: false,
      });
      if (ei.type === "error") criticalCount++;
      else warningCount++;
    }
  }

  // Auto-fix spacing: spasi ganda → single
  for (let i = 0; i < sections.length; i++) {
    if (sections[i].body) {
      sections[i].body = sections[i].body.replace(/\s{3,}/g, '  ');  // Triple+ → double
      sections[i].body = sections[i].body.replace(/^\s+|\s+$/gm, '');  // Trim lines
    }
  }

  // ════════════════════════════════════════════════════════
  // SUMMARY
  // ════════════════════════════════════════════════════════

  const passed = criticalCount === 0;
  const summary = buildSummary(issues, criticalCount, warningCount, autoFixedCount, sections.length);

  return {
    passed,
    issues,
    criticalCount,
    warningCount,
    autoFixedCount,
    article: auditedArticle,
    media: auditedMedia,
    summary,
  };
}

// ─── Summary Builder ───────────────────────────────────────

function buildSummary(
  issues: AuditIssue[],
  criticalCount: number,
  warningCount: number,
  autoFixedCount: number,
  sectionCount: number
): string {
  const parts: string[] = [];

  if (criticalCount > 0) {
    parts.push(`🛑 ${criticalCount} critical error${criticalCount > 1 ? "s" : ""}`);
  }
  if (warningCount > 0) {
    parts.push(`⚠️ ${warningCount} warning${warningCount > 1 ? "s" : ""}`);
  }
  if (autoFixedCount > 0) {
    parts.push(`🔧 ${autoFixedCount} auto-fixed`);
  }
  if (issues.length === 0) {
    return "✅ Semua validasi lolos! Artikel siap dikirim.";
  }

  const topIssues = issues.slice(0, 5).map(i =>
    `[${i.type === "error" ? "🛑" : "⚠️"}] ${i.message}`
  );

  return `📋 Audit: ${parts.join(" • ")} | ${sectionCount} section\n${topIssues.join("\n")}`;
}

// ─── Quick Check Function ──────────────────────────────────

/**
 * Quick validasi sebelum publish — throw kalau critical error.
 * Dipanggil dari article-publisher.ts sebelum kirim ke Discord.
 * 
 * Returns: { article, media } yang sudah di-audit & di-fix.
 */
export function auditBeforePublish(
  article: Article,
  mediaResults?: Array<{ type: string; sectionIndex: number; url: string | null; caption?: string } | null>
): { article: Article; media: ValidatedMedia[]; report: AuditReport } {
  const report = auditArticle(article, mediaResults);

  // Log audit summary
  console.log(`📋 Audit Report: ${report.summary.slice(0, 150)}`);

  // Kalo ada critical error, jangan dikirim!
  if (!report.passed) {
    const criticalIssues = report.issues.filter(i => i.type === "error");
    console.error(`🛑 AUDIT BLOCKED: ${criticalIssues.length} critical issue(s) ditemukan!`);
    for (const issue of criticalIssues) {
      console.error(`  🛑 ${issue.message} (${issue.location || "unknown"})`);
    }
  }

  return {
    article: report.article,
    media: report.media,
    report,
  };
}

// ─── Standalone Validator ─────────────────────────────────

/**
 * Validasi apakah artikel LAYAK dikirim ke Discord.
 * Cek lengkap: format, konten, media, platform, watermark.
 * 
 * @param article - Artikel yang akan dikirim
 * @returns { ok: boolean, issues: string[] }
 */
export function validateArticleForDiscord(article: Article): { ok: boolean; issues: string[] } {
  const report = auditArticle(article, []);
  const issues = report.issues.map(i => `${i.type === "error" ? "🛑" : "⚠️"} [${i.category}] ${i.message}`);

  return {
    ok: report.passed,
    issues,
  };
}

// ─── Export for external use ──────────────────────────────

export default {
  auditArticle,
  auditBeforePublish,
  validateArticleForDiscord,
  stripWatermarks,
  cleanGarbageChars,
};
